### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by ataiwo473** [hrttn/on-off-switch#1]
wp-content/plugins/on-off-switch-master/on-off-switch.php:39 Stack trace: #0 /Applications/MAMP/htdocs/liva2020/wp-admin/includes/plugin.php(2141): include() #1 /Applications/MAMP/htdocs/liva2020/wp-admin/plugins.php(175): plugin_sandbox_scrape('on-off-switch-m...') #2 {main} thrown in /Applications/MAMP/htdocs/liva2020/wp-content/plugins/on-off-switch-master/on-off-switch.php on line 39

**Comment by hrttn** [comment]
Hello,
Thanks for using the plugin!
I haven't touched it in a while. I will take a look at it soon to see what is causing the issue.

**Comment by ataiwo473** [comment]
great i tried to solve the problem but it was difficult

**Comment by hrttn** [comment]
@ataiwo473 Hey, I simplified the plugin a bit. Could you download it again from here and try again?

**Comment by ataiwo473** [comment]
wow this it so great. just checked it out. how can i add a timer and for when it should display thanks again

**Comment by hrttn** [comment]
@ataiwo473 Thanks a lot.
Unfortunately, it is not possible to add a timer without extra coding. This was mostly a test plugin for me and I do not intend to develop it more at the time.
